gazebo_ros_control/pid_gains:
  front_right_wheel__Rear: {p: 1500.0, i: 500.0, d: 1.0}
  front_left_wheel__Rear: {p: 1500.0, i: 500.0, d: 1.0}
  backward_right_wheel__Rear: {p: 1500.0, i: 500.0, d: 1.0}
  backward_left_wheel__Rear: {p: 1500.0, i: 500.0, d: 1.0}